# Numpy Package

In [1]:
import numpy as np
import timeit

## Document and Auto-completion in Jupyter

In [ ]:
# np.[TAB]
np.

In [ ]:
# Help document
np.random.normal

In [ ]:
# [Sh-Tab] to show function arguments
np.random.normal

## Vector & Matrix

In [ ]:
t = np.array([0, 1, 2, 3, 4, 5, 6])

print(t)
print(t.ndim) # rank
print(t.shape) # shape
print(t[0], t[1], t[-1])
print(t[2:5], t[4:-1])
print(t[:2], t[3:])

## Matrix multiplication

In [ ]:
vec_x = np.array([2, 5, 2])
mat_A = np.array([[1, 0.7, -0.2], [0.2, 1, 0.5], [0.2, -0.5, 1]])
print(vec_x, '\n', mat_A)

In [ ]:
# Vector * Vector (Matrix * Matrix): Component-wise
print(vec_x * vec_x, '\n')
print(mat_A * mat_A, '\n')

# Matrix x Vector ??: component-wise in each vector
print( mat_A * vec_x, '\n')
print( vec_x * mat_A, '\n') # Same

In [ ]:
mat_B = np.arange(12).reshape((3,4))
vec_y = np.arange(4)
print(mat_B, vec_y)
mat_B * vec_y 

In [ ]:
# Dot(inner) product
print( np.dot(vec_x, vec_x) )
print( vec_x.dot(vec_x) ) # same
print( vec_x@vec_x )

In [ ]:
# Matrix multiplication ?
print(mat_A @ mat_A, '\n')
# print(np.matmul(mat_A, mat_A), '\n')  # @ is exactly same as np.matmul

print(mat_A @ vec_x, '\n')  # vec_x is treated as a column vector

print(vec_x @ mat_A) # vec_x is treated as a row vector

In [ ]:
# Convert vecto to a matrix with single column
vec_x_col = vec_x[:,None]
#print( np.reshape(vec_x,(3,1)) )
#print( vec_x.reshape((3,1)) )

In [ ]:
vec_x + vec_x_col

In [ ]:
mat_A * vec_x[:, None]

In [ ]:
vec_x[None,:,None]

## N-d Array Initialization

In [ ]:
vec_y = np.ones(10)
vec_z = np.zeros((5,), dtype=int)
print(vec_z)

#mat_B = np.zeros((3,3))
#mat_B = np.zeros_like(mat_A)
mat_B = np.ones_like(mat_A)
print(mat_B)

x_norm = np.random.normal(10,2,size=(10000,5))
x_unif = np.random.uniform(size=(10000,5))

In [ ]:
x_norm

## Operations on Matrix (N-d array)

In [ ]:
# Axis 0: Column, Axis 1: Row
print( np.mean(x_norm, axis=0) )
print( np.std(x_norm, axis=0) )

In [ ]:
print( np.mean(x_norm) )
print( np.mean(x_norm,axis=0) )
print( np.mean(x_norm,axis=1) )
print( np.mean(x_norm,axis=(0,1)) )

In [ ]:
# Random Walk Simulation
x_rw = np.random.binomial(1,0.5,size=(1000,10))*2 - 1
x_rw

In [ ]:
x_cum = np.cumsum(x_rw, axis=0)
print(x_cum)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
plt.plot(x_cum)

In [ ]:
mat_B = np.arange(12).reshape((3,4))
vec_x = np.arange(4)
vec_y = np.arange(3)

In [ ]:
print(np.vstack([mat_B, mat_B]))
print(np.vstack([mat_B, vec_x]))

In [ ]:
print(np.hstack([mat_B, mat_B]))
#print(np.hstack([mat_B, vec_y]))
print(np.hstack([mat_B, vec_y[:,None]]))

# Vectorization is fast
* Using `for` or `while` loop is very slow
* Always find proper vectorization operation

In [2]:
# We're going to simulate the mean of the maximum of 20 normal distribution.
nn = 100000
x_norm = np.random.normal(size=(nn,20))

### Using `for` loop

In [3]:
start_time = timeit.default_timer()
x_max = np.ones(x_norm.shape[0])
for k in range(nn):
    x_max[k] = max(x_norm[k,:])
val = x_max.mean()
elapsed = timeit.default_timer() - start_time
print(f'mean={val}, time={elapsed}')

mean=1.8666412641973744, time=0.9044249999999998


### Vectorized Version

In [4]:
start_time = timeit.default_timer()
val = np.amax(x_norm, axis=1).mean()
elapsed = timeit.default_timer() - start_time
print(f'mean={val}, time={elapsed}')

mean=1.8666412641973744, time=0.015823000000004583


In [ ]:
assert np.all(x_max-x_max2 == 0)

## Array view and Copy
* Array is view shares the same memory space
* Any change in the view will make the same change in the original array

In [20]:
mat_B = np.arange(12).reshape((3,4))
vec_x = mat_B[1,]
#vec_x = mat_B[1,].copy()
#print(mat_B, vec_x)

In [21]:
vec_x[-2] = -99

In [22]:
print(mat_B, vec_x)

[[  0   1   2   3]
 [  4   5 -99   7]
 [  8   9  10  11]] [  4   5 -99   7]


In [23]:
# mat_C is not a view
mat_C = mat_B * 2
mat_C[1,1] = -99
print(mat_B, "\n\n", mat_C)

[[  0   1   2   3]
 [  4   5 -99   7]
 [  8   9  10  11]] 

 [[   0    2    4    6]
 [   8  -99 -198   14]
 [  16   18   20   22]]
